<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Assignment Submission - {{ $submission->student->full_name }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #1a202c; }
        .page-break { page-break-after: always; }
        .header { border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; color: #2d3748; }
        .meta { color: #718096; font-size: 12px; margin-top: 5px; }
        .image-container { text-align: center; margin-top: 20px; }
        .submission-image { max-width: 100%; max-height: 800px; border: 1px solid #edf2f7; border-radius: 8px; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; height: 50px; font-size: 10px; color: #a0aec0; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $submission->assignment->title }}</div>
        <div class="meta">
            Student: <strong>{{ $submission->student->full_name }}</strong> | 
            Subject: {{ $submission->assignment->subject->name }} | 
            Submitted: {{ $submission->submitted_at->format('M d, Y h:i A') }}
        </div>
    </div>

    @if($submission->content)
        <div style="margin-bottom: 40px; padding: 20px; background: #f7fafc; border-radius: 8px;">
            <div style="font-weight: bold; font-size: 12px; color: #4a5568; margin-bottom: 10px; text-transform: uppercase;">Submission Notes:</div>
            <div style="font-size: 14px; line-height: 1.6;">{!! nl2br(e($submission->content)) !!}</div>
        </div>
    @endif

    <div class="images">
        @foreach($images as $index => $image)
            <div class="image-container {{ $loop->last ? '' : 'page-break' }}" style="position: relative;">
                <div style="font-size: 10px; color: #a0aec0; margin-bottom: 10px;">Submission Exhibit #{{ $index + 1 }}</div>
                
                <div style="position: relative; display: inline-block;">
                    <img src="{{ $image }}" class="submission-image">
                    
                    {{-- Render Annotations for this image (only if NOT pre-flattened) --}}
                    @if(!($flattened ?? false))
                        @foreach($annotations as $a)
                            @if(($a['imageIndex'] ?? 0) == $index)
                                @if($a['type'] == 'stamp')
                                    <div style="position: absolute; left: {{ $a['x'] }}px; top: {{ $a['y'] }}px; color: {{ $a['color'] }}; font-size: 30px; font-weight: bold; transform: translate(-50%, -50%); -webkit-transform: translate(-50%, -50%);">
                                        {{ $a['stampType'] == 'tick' ? '✓' : '✗' }}
                                    </div>
                                @elseif($a['type'] == 'text')
                                    <div style="position: absolute; left: {{ $a['x'] }}px; top: {{ $a['y'] }}px; color: {{ $a['color'] }}; background: rgba(255,255,255,0.8); padding: 2px 5px; border-radius: 4px; font-size: 14px; font-weight: bold; border: 1px solid {{ $a['color'] }}; line-height: 1;">
                                        {{ $a['text'] }}
                                    </div>
                                @endif
                            @endif
                        @endforeach
                    @endif
                </div>
            </div>
        @endforeach
    </div>

    <div class="footer">
        Generated by Academic Portal • {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>
